# Generated by Django 3.0.3 on 2020-09-09 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('weight', models.IntegerField()),
            ],
            options={
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('remark', models.TextField()),
                ('url', models.URLField()),
                ('title', models.TextField()),
                ('weight', models.IntegerField()),
                ('menu', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='webstack.Menu')),
            ],
            options={
                'db_table': 'website',
            },
        ),
    ]
