# Generated by Django 3.0.3 on 2020-09-09 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webstack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='webstack.Menu'),
        ),
    ]
