# Generated by Django 3.0.3 on 2020-09-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstack', '0002_auto_20200909_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='img',
            field=models.URLField(null=True),
        ),
    ]
