# Generated by Django 3.0.3 on 2020-09-09 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstack', '0003_website_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='weight',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='website',
            name='weight',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)]),
        ),
    ]
