# Generated by Django 3.0.3 on 2020-09-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstack', '0004_auto_20200909_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='website',
            name='weight',
            field=models.IntegerField(default=1, max_length=2),
        ),
    ]
