# Generated by Django 3.0.3 on 2020-09-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstack', '0005_auto_20200910_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='weight',
            field=models.IntegerField(default=1),
        ),
    ]
