# Generated by Django 3.0.3 on 2020-09-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstack', '0008_auto_20200910_0023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': '分类菜单', 'verbose_name_plural': '分类菜单'},
        ),
        migrations.AlterModelOptions(
            name='website',
            options={'verbose_name': '站点', 'verbose_name_plural': '站点'},
        ),
        migrations.RemoveField(
            model_name='website',
            name='img',
        ),
        migrations.AddField(
            model_name='menu',
            name='icon',
            field=models.TextField(default='linecons-star'),
        ),
        migrations.AddField(
            model_name='website',
            name='icon',
            field=models.URLField(default='https://aupicgo.oss-cn-shanghai.aliyuncs.com/img/20200910125957.ico'),
        ),
        migrations.AlterField(
            model_name='website',
            name='name',
            field=models.TextField(verbose_name='站点名称'),
        ),
        migrations.AlterField(
            model_name='website',
            name='remark',
            field=models.TextField(verbose_name=''),
        ),
    ]
