# Generated by Django 3.0.3 on 2020-09-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstack', '0009_auto_20200910_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': '分组', 'verbose_name_plural': '分组'},
        ),
        migrations.AlterModelOptions(
            name='website',
            options={'verbose_name': '网站', 'verbose_name_plural': '网站'},
        ),
        migrations.RemoveField(
            model_name='website',
            name='remark',
        ),
        migrations.AddField(
            model_name='website',
            name='description',
            field=models.TextField(default='', verbose_name='网站描述'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.TextField(default='linecons-star', verbose_name='分组图标'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.TextField(verbose_name='分组名'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='weight',
            field=models.IntegerField(default=1, verbose_name='分组权重'),
        ),
        migrations.AlterField(
            model_name='website',
            name='name',
            field=models.TextField(verbose_name='网站名称'),
        ),
    ]
