# Generated by Django 3.0.3 on 2020-09-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstack', '0010_auto_20200910_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='title',
            field=models.TextField(verbose_name='原始标题'),
        ),
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.URLField(verbose_name='网站链接'),
        ),
    ]
