# Generated by Django 3.0.3 on 2020-09-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstack', '0011_auto_20200910_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='icon',
            field=models.URLField(default='https://aupicgo.oss-cn-shanghai.aliyuncs.com/img/20200910125957.ico', verbose_name='网站图标'),
        ),
        migrations.AlterField(
            model_name='website',
            name='weight',
            field=models.IntegerField(default=1, verbose_name='网站权重'),
        ),
    ]
